repos:
-   repo: "https://github.com/ambv/black"
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3

-   repo: "https://github.com/asottile/blacken-docs"
    rev: 1.13.0
    hooks:
    - id: blacken-docs
      additional_dependencies: [black==23.3.0]
      language_version: python3

-   repo: "https://github.com/pycqa/isort"
    rev: 5.12.0
    hooks:
    - id: isort
      language_version: python3

-   repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v2.4.0
    hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: flake8
      additional_dependencies: [flake8-bugbear==18.2.0]
      language_version: python3
